name: Create Release with major tag
# example: gh workflow run release.yml -f tag_name=v1.1.4 -f draft=true
on:
  push:
    branches:
      - feat/release-with-major-tag-update
    inputs:
      tag_name:
        type: string
        required: true
      draft:
        type: boolean
        description: Draft release
        default: false
      prerelease:
        type: boolean
        description: Prerelease
        default: false
      first-release:
        type: boolean
        description: First release
        default: false

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      TEST_TAG: v0.x.2

    outputs:
      version_number: ${{ steps.set-version-number.outputs.version_number }}
      major_tag: ${{ steps.set-major-tag.outputs.major_tag }}

    steps:
      - name: Set version number with v
        run: |
          echo "VERSION_NUMBER=$(echo ${{ env.TEST_TAG }})" >> $GITHUB_ENV

      - name: Set major tag with v
        run: |
          echo "MAJOR_TAG=$(echo ${{ env.VERSION_NUMBER }} | cut -d. -f1)" >> $GITHUB_ENV    

      - name: Clone sources
        uses: actions/checkout@v3

      - name: Create Tag ${{ github.event.inputs.tag_name }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.VERSION_NUMBER }}",
              sha: context.sha
            })

      - name: Prepare release notes
        run: |
          # Retrieve release body and remove ---
          VERSION_RELEASE_NOTES=$(awk -v ver="[${{ env.VERSION_NUMBER }}]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/${{ env.VERSION_NUMBER }})" '/^## / { if (p) { exit }; if ($2 == ver) { p=1; next} } p && NF' CHANGELOG.md | sed ':a;N;$!ba;s/\n---/ /g')
          echo "$VERSION_RELEASE_NOTES" >> CHANGELOG.txt

      - name: Create release ${{ env.VERSION_NUMBER }}
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.txt
          name: ${{ env.VERSION_NUMBER }}
          tag_name: ${{ env.VERSION_NUMBER }}
          draft: false
          prerelease: false

      - name: Set version number as output
        id: set-version-number
        run: echo "version_number=${{ env.VERSION_NUMBER}}" >> $GITHUB_OUTPUT

      - name: Set version number as output
        id: set-major-tag
        run: echo "major_tag=${{ env.MAJOR_TAG}}" >> $GITHUB_OUTPUT


  update-major-tag:
    name: Update major tag
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Move the major tag version
        run: git tag -f ${{needs.create-release.outputs.major_tag}} ${{needs.create-release.outputs.version_number}}

      - name: Push the updated major tag version
        run: git push origin ${{needs.create-release.outputs.major_tag}} --force
